{% set name = "fast-barnes-py" %}
{% set version = "2.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/fast-barnes-py-{{ version }}.tar.gz
  sha256: c73afaabb93898af4918f765aa181a269b07a46c71d603be85dbe8102bafd99f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - numpy
    - scipy
    - numba

test:
  imports:
    - fastbarnes
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/MeteoSwiss/fast-barnes-py/
  summary: Fast Barnes Interpolation
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
