{% set name = "fast-barnes-py" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/fast-barnes-py-{{ version }}.tar.gz
  sha256: 1273f85ba85cd9620f6110404fd0f5f5084367e4da75b278688232c9d61be314
  patches:
    - missing_long_description.patch

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - numpy
    - scipy
    - numba

test:
  imports:
    - fastbarnes
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/MeteoSwiss/fast-barnes-py/
  summary: Fast Barnes Interpolation
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
